name: Sync to GitLab VPS

on:
  push:
    branches: [ "main", "master" ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to GitLab VPS
        run: |
          # Perbaikan: Hapus tanda '#' dan tambahkan '.git' di akhir
          GITLAB_URL="gitlab.kazulab.my.id/Reval/github-khuanzah.git"
          
          git push --prune "https://gitlab-ci-token:${{ secrets.GITLAB_TOKEN }}@${GITLAB_URL}" refs/heads/*:refs/heads/* refs/tags/*:refs/tags/*
